version: '3.8'
services:
    php-apache-environment:
        container_name: php-apache
        build: ./.docker
        volumes:
            - ./backend:/var/www/html/
        ports:
            - 8000:80

    db:
        container_name: db
        image: mysql:latest
        restart: always
        environment:
            - MYSQL_ROOT_PASSWORD=
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes
        ports:
            - '3306:3306'

    phpmyadmin:
        container_name: phpmyadmin
        image: phpmyadmin:latest
        ports:
            - '8080:80'
        restart: always
        environment:
            PMA_HOST: db
        depends_on:
            - db
